//===- ConvertHFusionToUpstream.cpp ---------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements converting HFusion operations
// to upstream dialect equivalents for precision verification on the CPU
// execution engine (mlir-cpu-runner).
//
//===----------------------------------------------------------------------===//

#include "bishengir/Dialect/HFusion/IR/HFusion.h"
#include "bishengir/ExecutionEngine/Passes.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"

// Include the Pass base class code automatically generated by TableGen
namespace mlir {
#define GEN_PASS_DEF_EXECUTIONENGINEHFUSIONTOUPSTREAMCONVERSION
#include "bishengir/ExecutionEngine/Passes.h.inc"
} // namespace mlir

namespace {

using namespace mlir;

// =======================================================================
// HistogramOp Lowering (1D Flattening + SCF Scalar Loop)
// =======================================================================
struct RewriteHistogramOp : public OpRewritePattern<hfusion::HistogramOp> {
  using OpRewritePattern<hfusion::HistogramOp>::OpRewritePattern;

  LogicalResult matchAndRewrite(hfusion::HistogramOp op,
                                PatternRewriter &rewriter) const override {
    Location loc = op.getLoc();
    Value input = op.getInput();
    Value mask = op.getMask();

    auto inputTy = dyn_cast<RankedTensorType>(input.getType());
    auto outTy = dyn_cast<RankedTensorType>(op.getResult().getType());

    if (!inputTy || !outTy)
      return failure();

    SmallVector<ReassociationIndices> reassoc;

    // 1. Flatten arbitrary-rank tensors to 1D.
    Value flatInput = input;
    if (inputTy.getRank() > 1) {
      ReassociationIndices indices;
      for (int64_t i = 0; i < inputTy.getRank(); ++i) {
        indices.push_back(i);
      }
      reassoc.push_back(indices);

      int64_t flatSize = inputTy.hasStaticShape() ? inputTy.getNumElements()
                                                  : ShapedType::kDynamic;
      auto flatTy = RankedTensorType::get({flatSize}, inputTy.getElementType());
      flatInput =
          rewriter.create<tensor::CollapseShapeOp>(loc, flatTy, input, reassoc);
    }
    Value flatMask = mask;
    if (mask) {
      auto maskTy = cast<RankedTensorType>(mask.getType());
      if (maskTy.getRank() > 1) {
        int64_t flatMaskSize = maskTy.hasStaticShape() ? maskTy.getNumElements()
                                                       : ShapedType::kDynamic;
        auto flatMaskTy =
            RankedTensorType::get({flatMaskSize}, maskTy.getElementType());
        flatMask = rewriter.create<tensor::CollapseShapeOp>(loc, flatMaskTy,
                                                            mask, reassoc);
      }
    }

    // 2. Initialize histogram bins with zeros using linalg.fill.
    Type outElemTy = outTy.getElementType();
    Value zero = rewriter.create<arith::ConstantOp>(
        loc, rewriter.getZeroAttr(outElemTy));
    Value emptyHist =
        rewriter.create<tensor::EmptyOp>(loc, outTy.getShape(), outElemTy);
    Value initHist =
        rewriter.create<linalg::FillOp>(loc, zero, emptyHist).getResult(0);

    // 3. Construct the scf.for loop for binning.
    Value c0 = rewriter.create<arith::ConstantIndexOp>(loc, 0);
    Value c1 = rewriter.create<arith::ConstantIndexOp>(loc, 1);
    Value upperBound = rewriter.create<tensor::DimOp>(loc, flatInput, c0);
    Value numBins =
        rewriter.create<arith::ConstantIndexOp>(loc, outTy.getShape()[0]);

    auto forOp = rewriter.create<scf::ForOp>(loc, c0, upperBound, c1,
                                             ValueRange{initHist});
    {
      OpBuilder::InsertionGuard guard(rewriter);
      rewriter.setInsertionPointToStart(forOp.getBody());

      Value iv = forOp.getInductionVar();
      Value curHist = forOp.getRegionIterArgs()[0];

      // Extract data and cast to index.
      Value elem =
          rewriter.create<tensor::ExtractOp>(loc, flatInput, ValueRange{iv});
      Value indexVal = rewriter.create<arith::IndexCastOp>(
          loc, rewriter.getIndexType(), elem);

      // Boundary safety check: 0 <= indexVal < numBins.
      Value isGeZero = rewriter.create<arith::CmpIOp>(
          loc, arith::CmpIPredicate::sge, indexVal, c0);
      Value isLtBins = rewriter.create<arith::CmpIOp>(
          loc, arith::CmpIPredicate::slt, indexVal, numBins);
      Value isValid = rewriter.create<arith::AndIOp>(loc, isGeZero, isLtBins);
      if (mask) {
        Value maskVal =
            rewriter.create<tensor::ExtractOp>(loc, flatMask, ValueRange{iv});
        isValid = rewriter.create<arith::AndIOp>(loc, isValid, maskVal);
      }
      auto ifOp = rewriter.create<scf::IfOp>(loc, curHist.getType(), isValid,
                                             /*withElseRegion=*/true);

      // Then branch: valid index, accumulate by 1.
      {
        OpBuilder::InsertionGuard thenGuard(rewriter);
        rewriter.setInsertionPointToStart(&ifOp.getThenRegion().front());

        Value oldVal = rewriter.create<tensor::ExtractOp>(loc, curHist,
                                                          ValueRange{indexVal});
        Value one = rewriter.create<arith::ConstantOp>(
            loc, rewriter.getIntegerAttr(outElemTy, 1));
        Value newVal = rewriter.create<arith::AddIOp>(loc, oldVal, one);
        Value nextHist = rewriter.create<tensor::InsertOp>(
            loc, newVal, curHist, ValueRange{indexVal});

        rewriter.create<scf::YieldOp>(loc, nextHist);
      }

      // Else branch: out-of-bounds index, keep the original histogram.
      {
        OpBuilder::InsertionGuard elseGuard(rewriter);
        rewriter.setInsertionPointToStart(&ifOp.getElseRegion().front());
        rewriter.create<scf::YieldOp>(loc, curHist);
      }

      rewriter.create<scf::YieldOp>(loc, ifOp.getResult(0));
    }

    // 4. Replace the original operation.
    rewriter.replaceOp(op, forOp.getResult(0));
    return success();
  }
};

// =======================================================================
// IsNanOp Lowering
// =======================================================================
struct RewriteHFusionIsNanOp : public OpRewritePattern<hfusion::IsNanOp> {
  using OpRewritePattern<hfusion::IsNanOp>::OpRewritePattern;

  LogicalResult matchAndRewrite(hfusion::IsNanOp op,
                                PatternRewriter &rewriter) const override {
    auto inputType = dyn_cast<RankedTensorType>(op.getInput().getType());
    auto resultType = dyn_cast<RankedTensorType>(op.getResult().getType());
    if (!inputType || !resultType)
      return failure();

    auto elemType = dyn_cast<FloatType>(inputType.getElementType());
    if (!elemType)
      return failure();

    const Location loc = op.getLoc();
    const int64_t rank = inputType.getRank();

    SmallVector<Value> dynamicSizes;
    dynamicSizes.reserve(rank);
    for (int64_t i = 0; i < rank; ++i)
      if (inputType.isDynamicDim(i))
        dynamicSizes.push_back(
            rewriter.create<tensor::DimOp>(loc, op.getInput(), i));

    Value initTensor = rewriter.create<tensor::EmptyOp>(
        loc, resultType.getShape(), resultType.getElementType(), dynamicSizes);

    SmallVector<AffineMap> indexingMaps(
        2, rewriter.getMultiDimIdentityMap(rank));
    SmallVector<utils::IteratorType> iteratorTypes(
        rank, utils::IteratorType::parallel);

    auto genericOp = rewriter.create<linalg::GenericOp>(
        loc, resultType, ValueRange{op.getInput()}, ValueRange{initTensor},
        indexingMaps, iteratorTypes,
        [&](OpBuilder &b, Location nestedLoc, ValueRange args) {
          Value isNan = b.create<arith::CmpFOp>(
              nestedLoc, arith::CmpFPredicate::UNO, args[0], args[0]);
          b.create<linalg::YieldOp>(nestedLoc, isNan);
        });

    rewriter.replaceOp(op, genericOp.getResult(0));
    return success();
  }
};

// =======================================================================
// Deinterleaveop Lowering
// =======================================================================
struct RewriteHFusionDeinterleaveOp
    : public OpRewritePattern<hfusion::DeinterleaveOp> {
  using OpRewritePattern<hfusion::DeinterleaveOp>::OpRewritePattern;

  LogicalResult matchAndRewrite(hfusion::DeinterleaveOp op,
                                PatternRewriter &rewriter) const override {
    auto inputType = dyn_cast<RankedTensorType>(op.getInput().getType());
    if (!inputType)
      return failure();

    if (op.getOutput().empty())
      return failure();
    auto resultType = dyn_cast<RankedTensorType>(op.getResult(0).getType());
    if (!resultType)
      return failure();

    const int64_t rank    = inputType.getRank();
    const int64_t chanIdx = op.getDeInterLeaveChannelIdx(); // -1, 0, 1
    // -1(all) equals to even，offset=0；0=even；1=odd
    const int64_t offset  = (chanIdx == 1) ? 1 : 0;
    const Location loc    = op.getLoc();
    MLIRContext *ctx      = rewriter.getContext();

    // 1. prepare empty tensor
    SmallVector<Value> dynamicSizes;
    for (int64_t i = 0; i < rank - 1; ++i) {
      if (resultType.isDynamicDim(i))
        dynamicSizes.push_back(
            rewriter.create<tensor::DimOp>(loc, op.getInput(), i));
    }
    if (resultType.isDynamicDim(rank - 1)) {
      Value lastDim =
          rewriter.create<tensor::DimOp>(loc, op.getInput(), rank - 1);
      Value two = rewriter.create<arith::ConstantIndexOp>(loc, 2);
      dynamicSizes.push_back(
          rewriter.create<arith::DivUIOp>(loc, lastDim, two));
    }

    Value initTensor = rewriter.create<tensor::EmptyOp>(
        loc, resultType.getShape(), resultType.getElementType(), dynamicSizes);

    // 2. indexing maps
    //    input:  (d0,...,d_{r-1}) -> (d0,...,d_{r-2}, d_{r-1}*2 + offset)
    //    output: identity
    SmallVector<AffineExpr> inputExprs;
    for (int64_t i = 0; i < rank - 1; ++i)
      inputExprs.push_back(getAffineDimExpr(i, ctx));
    inputExprs.push_back(getAffineDimExpr(rank - 1, ctx) * 2 + offset);

    SmallVector<AffineMap> indexingMaps = {
        AffineMap::get(rank, 0, inputExprs, ctx),
        rewriter.getMultiDimIdentityMap(rank)};

    SmallVector<utils::IteratorType> iterTypes(rank,
                                               utils::IteratorType::parallel);

    // 3. linalg.generic：body yield 
    auto genericOp = rewriter.create<linalg::GenericOp>(
        loc, resultType,
        ValueRange{op.getInput()}, ValueRange{initTensor},
        indexingMaps, iterTypes,
        [](OpBuilder &b, Location nestedLoc, ValueRange args) {
          b.create<linalg::YieldOp>(nestedLoc, args[0]);
        });

    rewriter.replaceOp(op, genericOp.getResult(0));
    return success();
  }
};

// =======================================================================
// Pass Definition
// =======================================================================
struct ConvertHFusionToUpstream
    : public impl::ExecutionEngineHFusionToUpstreamConversionBase<
          ConvertHFusionToUpstream> {

  using Base::Base;

  void runOnOperation() override {
    auto &ctx = getContext();
    RewritePatternSet patterns(&ctx);

    // Register all HFusion-to-CPU lowering patterns here.
    patterns.add<RewriteHistogramOp>(&ctx);
    patterns.add<RewriteHFusionIsNanOp>(&ctx);
    patterns.add<RewriteHFusionDeinterleaveOp>(&ctx);

    // Future operations like CumprodOp, AtomicXchgOp, etc., should be added below.
    //
    // patterns.add<RewriteXXXXX>(&ctx);

    // Apply all rewrite patterns greedily.
    if (failed(applyPatternsAndFoldGreedily(getOperation(),
                                            std::move(patterns)))) {
      signalPassFailure();
    }
  }
};

} // namespace

// =======================================================================
// Pass Creation
// =======================================================================
std::unique_ptr<Pass>
mlir::execution_engine::createConvertHFusionToUpstreamPass() {
  return std::make_unique<ConvertHFusionToUpstream>();
}